version: '1'
services:
  frontend:
    image: 'sankkket24/front-end-server:latest'
    ports:
      - "80:3000"
    depends_on:
      - backend
  backend:
    image: 'sankkket24/back-end-server:latest'
    ports:
      - '9090:9090'

